local awful = require("awful")
--   awful.spawn.once("mpd")
--   awful.spawn.once("mpDris2")
awful.spawn.once("picom")
awful.spawn.once("xsettingsd")
awful.spawn.once("nm-applet")
-- awful.spawn.once("redshift")
